### ISSUE TITLE
Leading UI

### ISSUE THREAD

**Issue by Dalstroem** [Dalstroem/Walter#3]
The leading UI is the first thing you see, when starting the application. This consists mainly of whitelisting and administration of shows.

**Tasks**

- [x] Add new show to whitelist.
- [x] Edit show title.
- [x] Remove show from whitelist.
- [x] Disable show.
- [x] Filter by title.
